### ISSUE TITLE
Add option to add new avatars

### ISSUE THREAD

**Issue by dmey** [letmaik/avatar-animator#19]
It would be useful to add an option under the avatar tab to add new avatars.

**Comment by letmaik** [comment]
I think that's overkill since it won't happen often. I think changing the way the designs are loaded would be better, so that all you have to do is copy the svg into the folder. Currently all designs are listed explicitly in the code.

**Comment by letmaik** [comment]
Turns out there's already a way to load custom SVGs. You just drag and drop the file into the window. I think that's good enough for now, right?

**Comment by dmey** [comment]
OK -- I have now updated https://github.com/letmaik/avatar-animator/pull/20 accordingly. Once that's merged in we can close this one.
